//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jbposs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.venta = new HashSet<venta>();
        }
    
        public int id_cliente { get; set; }
        public int id_provincia { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(50, ErrorMessage = "El nombre debe tener como máximo 50 caracteres.")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El apellido es obligatorio.")]
        [StringLength(50, ErrorMessage = "El apellido debe tener como máximo 50 caracteres.")]
        public string apellido { get; set; }

        public string email { get; set; }

        [StringLength(100, ErrorMessage = "La longitud máxima del domicilio es de 100 caracteres.")]
        public string domicilio { get; set; }

        public string telefono { get; set; }

        [Required(ErrorMessage = "El DNI es obligatorio.")]
        [StringLength(10, ErrorMessage = "El DNI debe tener como máximo 10 caracteres.")]
        public string dni { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
        public virtual provincia provincia { get; set; }
    }
}
